---
- name: Render lightningstream.yml config
  ansible.builtin.template:
    src: lightningstream.yml.j2
    dest: /etc/lightningstream.yml
    mode: '0644'
  notify: Reload systemd

- name: Enable and start lightningstream
  ansible.builtin.systemd:
    name: lightningstream
    enabled: true
    state: started
    daemon_reload: true
